#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colcon-cmake
Version  : 0.2.4
Release  : 4
URL      : https://files.pythonhosted.org/packages/b7/44/c23d6e2785ff71f609d959653a8db6d2e0cf8c36aa2f10f371d83ee61f00/colcon-cmake-0.2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/b7/44/c23d6e2785ff71f609d959653a8db6d2e0cf8c36aa2f10f371d83ee61f00/colcon-cmake-0.2.4.tar.gz
Summary  : Extension for colcon to support CMake packages.
Group    : Development/Tools
License  : Apache-2.0
Requires: colcon-cmake-python = %{version}-%{release}
Requires: colcon-cmake-python3 = %{version}-%{release}
Requires: colcon-core
Requires: colcon-library-path
BuildRequires : buildreq-distutils3

%description
============

%package python
Summary: python components for the colcon-cmake package.
Group: Default
Requires: colcon-cmake-python3 = %{version}-%{release}

%description python
python components for the colcon-cmake package.


%package python3
Summary: python3 components for the colcon-cmake package.
Group: Default
Requires: python3-core

%description python3
python3 components for the colcon-cmake package.


%prep
%setup -q -n colcon-cmake-0.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539915459
python3 setup.py build

%install
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
